services:

  github-runner:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    container_name: github-runner
    env_file: /home/admin/docker/runner/.env
    environment:
      RUNNER_SCOPE: repo
      REPO_URL: ${GITHUB_RUNNER_REPO_URL}
      RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      LABELS: ${RUNNER_LABELS}
      RUNNER_WORKDIR: /tmp/runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/docker/runner/runner:/tmp/runner
      - /home/admin/docker:/home/admin/docker
