name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: [self-hosted, gateway]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          git pull origin main
          cd hosts/gateway
          docker compose up -d
