name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: [self-hosted, gateway]
    steps:
      - uses: actions/checkout@v3
        with:
          path: /home/johan/docker

      - name: Run deploy script
        working-directory: /home/johan/docker
        run: bash ./deploy.sh
