name: Deploy

on: [push]

# Verhindert, dass sich mehrere Pushes zu einem Job-Stau aufstauen.
concurrency:
  group: deploy-gateway
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, gateway]
    steps:
      - name: Deploy
        run: |
          git config --global --add safe.directory /home/admin/docker
          cd /home/admin/docker
          git fetch origin main
          git reset --hard origin/main
          cd hosts/gateway
          docker compose up -d --remove-orphans
